export declare class FastDomNode<T extends HTMLElement> {
    readonly domNode: T;
    private _maxWidth;
    private _width;
    private _height;
    private _top;
    private _left;
    private _bottom;
    private _right;
    private _fontFamily;
    private _fontWeight;
    private _fontSize;
    private _lineHeight;
    private _letterSpacing;
    private _className;
    private _display;
    private _position;
    private _visibility;
    private _layerHint;
    constructor(domNode: T);
    setMaxWidth(maxWidth: number): void;
    setWidth(width: number): void;
    unsetWidth(): void;
    setHeight(height: number): void;
    unsetHeight(): void;
    setTop(top: number): void;
    unsetTop(): void;
    setLeft(left: number): void;
    setBottom(bottom: number): void;
    setRight(right: number): void;
    setFontFamily(fontFamily: string): void;
    setFontWeight(fontWeight: string): void;
    setFontSize(fontSize: number): void;
    setLineHeight(lineHeight: number): void;
    setLetterSpacing(letterSpacing: number): void;
    setClassName(className: string): void;
    toggleClassName(className: string, shouldHaveIt?: boolean): void;
    setDisplay(display: string): void;
    setPosition(position: string): void;
    setVisibility(visibility: string): void;
    setLayerHinting(layerHint: boolean): void;
    setAttribute(name: string, value: string): void;
    getAttribute(name: string): string;
    removeAttribute(name: string): void;
    hasAttribute(name: string): boolean;
    appendChild(child: FastDomNode<any>): void;
    removeChild(child: FastDomNode<any>): void;
}
export declare function createFastDomNode<T extends HTMLElement>(domNode: T): FastDomNode<T>;
