import Event from 'vs/base/common/event';
import { TPromise } from 'vs/base/common/winjs.base';
import URI from 'vs/base/common/uri';
import { TextFileEditorModel } from 'vs/workbench/services/textfile/common/textFileEditorModel';
import { ITextFileEditorModel, ITextFileEditorModelManager, TextFileModelChangeEvent, IModelLoadOrCreateOptions } from 'vs/workbench/services/textfile/common/textfiles';
import { ILifecycleService } from 'vs/platform/lifecycle/common/lifecycle';
import { IInstantiationService } from 'vs/platform/instantiation/common/instantiation';
export declare class TextFileEditorModelManager implements ITextFileEditorModelManager {
    private lifecycleService;
    private instantiationService;
    private toUnbind;
    private _onModelDisposed;
    private _onModelContentChanged;
    private _onModelDirty;
    private _onModelSaveError;
    private _onModelSaved;
    private _onModelReverted;
    private _onModelEncodingChanged;
    private _onModelOrphanedChanged;
    private _onModelsDirtyEvent;
    private _onModelsSaveError;
    private _onModelsSaved;
    private _onModelsReverted;
    private mapResourceToDisposeListener;
    private mapResourceToStateChangeListener;
    private mapResourceToModelContentChangeListener;
    private mapResourceToModel;
    private mapResourceToPendingModelLoaders;
    constructor(lifecycleService: ILifecycleService, instantiationService: IInstantiationService);
    private registerListeners();
    readonly onModelDisposed: Event<URI>;
    readonly onModelContentChanged: Event<TextFileModelChangeEvent>;
    readonly onModelDirty: Event<TextFileModelChangeEvent>;
    readonly onModelSaveError: Event<TextFileModelChangeEvent>;
    readonly onModelSaved: Event<TextFileModelChangeEvent>;
    readonly onModelReverted: Event<TextFileModelChangeEvent>;
    readonly onModelEncodingChanged: Event<TextFileModelChangeEvent>;
    readonly onModelOrphanedChanged: Event<TextFileModelChangeEvent>;
    readonly onModelsDirty: Event<TextFileModelChangeEvent[]>;
    readonly onModelsSaveError: Event<TextFileModelChangeEvent[]>;
    readonly onModelsSaved: Event<TextFileModelChangeEvent[]>;
    readonly onModelsReverted: Event<TextFileModelChangeEvent[]>;
    private debounce(event);
    protected debounceDelay(): number;
    get(resource: URI): ITextFileEditorModel;
    loadOrCreate(resource: URI, options?: IModelLoadOrCreateOptions): TPromise<ITextFileEditorModel>;
    getAll(resource?: URI, filter?: (model: ITextFileEditorModel) => boolean): ITextFileEditorModel[];
    add(resource: URI, model: ITextFileEditorModel): void;
    remove(resource: URI): void;
    clear(): void;
    disposeModel(model: TextFileEditorModel): void;
    dispose(): void;
}
