import URI from 'vs/base/common/uri';
import { TPromise } from 'vs/base/common/winjs.base';
import * as vscode from 'vscode';
import { ISingleEditOperation } from 'vs/editor/common/editorCommon';
import * as modes from 'vs/editor/common/modes';
import { ExtHostHeapService } from 'vs/workbench/api/node/extHostHeapService';
import { ExtHostDocuments } from 'vs/workbench/api/node/extHostDocuments';
import { ExtHostCommands } from 'vs/workbench/api/node/extHostCommands';
import { ExtHostDiagnostics } from 'vs/workbench/api/node/extHostDiagnostics';
import { ExtHostLanguageFeaturesShape, IRawColorInfo, IMainContext } from './extHost.protocol';
import { IPosition } from 'vs/editor/common/core/position';
import { IRange } from 'vs/editor/common/core/range';
export declare class ExtHostLanguageFeatures implements ExtHostLanguageFeaturesShape {
    private static _handlePool;
    private _proxy;
    private _telemetry;
    private _documents;
    private _commands;
    private _heapService;
    private _diagnostics;
    private _adapter;
    private _colorFormatCache;
    constructor(mainContext: IMainContext, documents: ExtHostDocuments, commands: ExtHostCommands, heapMonitor: ExtHostHeapService, diagnostics: ExtHostDiagnostics);
    private _createDisposable(handle);
    private _nextHandle();
    private _withAdapter<A, R>(handle, ctor, callback);
    registerDocumentSymbolProvider(selector: vscode.DocumentSelector, provider: vscode.DocumentSymbolProvider): vscode.Disposable;
    $provideDocumentSymbols(handle: number, resource: URI): TPromise<modes.SymbolInformation[]>;
    registerCodeLensProvider(selector: vscode.DocumentSelector, provider: vscode.CodeLensProvider): vscode.Disposable;
    $provideCodeLenses(handle: number, resource: URI): TPromise<modes.ICodeLensSymbol[]>;
    $resolveCodeLens(handle: number, resource: URI, symbol: modes.ICodeLensSymbol): TPromise<modes.ICodeLensSymbol>;
    registerDefinitionProvider(selector: vscode.DocumentSelector, provider: vscode.DefinitionProvider): vscode.Disposable;
    $provideDefinition(handle: number, resource: URI, position: IPosition): TPromise<modes.Definition>;
    registerImplementationProvider(selector: vscode.DocumentSelector, provider: vscode.ImplementationProvider): vscode.Disposable;
    $provideImplementation(handle: number, resource: URI, position: IPosition): TPromise<modes.Definition>;
    registerTypeDefinitionProvider(selector: vscode.DocumentSelector, provider: vscode.TypeDefinitionProvider): vscode.Disposable;
    $provideTypeDefinition(handle: number, resource: URI, position: IPosition): TPromise<modes.Definition>;
    registerHoverProvider(selector: vscode.DocumentSelector, provider: vscode.HoverProvider, extensionId?: string): vscode.Disposable;
    $provideHover(handle: number, resource: URI, position: IPosition): TPromise<modes.Hover>;
    registerDocumentHighlightProvider(selector: vscode.DocumentSelector, provider: vscode.DocumentHighlightProvider): vscode.Disposable;
    $provideDocumentHighlights(handle: number, resource: URI, position: IPosition): TPromise<modes.DocumentHighlight[]>;
    registerReferenceProvider(selector: vscode.DocumentSelector, provider: vscode.ReferenceProvider): vscode.Disposable;
    $provideReferences(handle: number, resource: URI, position: IPosition, context: modes.ReferenceContext): TPromise<modes.Location[]>;
    registerCodeActionProvider(selector: vscode.DocumentSelector, provider: vscode.CodeActionProvider): vscode.Disposable;
    $provideCodeActions(handle: number, resource: URI, range: IRange): TPromise<modes.Command[]>;
    registerDocumentFormattingEditProvider(selector: vscode.DocumentSelector, provider: vscode.DocumentFormattingEditProvider): vscode.Disposable;
    $provideDocumentFormattingEdits(handle: number, resource: URI, options: modes.FormattingOptions): TPromise<ISingleEditOperation[]>;
    registerDocumentRangeFormattingEditProvider(selector: vscode.DocumentSelector, provider: vscode.DocumentRangeFormattingEditProvider): vscode.Disposable;
    $provideDocumentRangeFormattingEdits(handle: number, resource: URI, range: IRange, options: modes.FormattingOptions): TPromise<ISingleEditOperation[]>;
    registerOnTypeFormattingEditProvider(selector: vscode.DocumentSelector, provider: vscode.OnTypeFormattingEditProvider, triggerCharacters: string[]): vscode.Disposable;
    $provideOnTypeFormattingEdits(handle: number, resource: URI, position: IPosition, ch: string, options: modes.FormattingOptions): TPromise<ISingleEditOperation[]>;
    registerWorkspaceSymbolProvider(provider: vscode.WorkspaceSymbolProvider): vscode.Disposable;
    $provideWorkspaceSymbols(handle: number, search: string): TPromise<modes.SymbolInformation[]>;
    $resolveWorkspaceSymbol(handle: number, symbol: modes.SymbolInformation): TPromise<modes.SymbolInformation>;
    registerRenameProvider(selector: vscode.DocumentSelector, provider: vscode.RenameProvider): vscode.Disposable;
    $provideRenameEdits(handle: number, resource: URI, position: IPosition, newName: string): TPromise<modes.WorkspaceEdit>;
    registerCompletionItemProvider(selector: vscode.DocumentSelector, provider: vscode.CompletionItemProvider, triggerCharacters: string[]): vscode.Disposable;
    $provideCompletionItems(handle: number, resource: URI, position: IPosition): TPromise<modes.ISuggestResult>;
    $resolveCompletionItem(handle: number, resource: URI, position: IPosition, suggestion: modes.ISuggestion): TPromise<modes.ISuggestion>;
    registerSignatureHelpProvider(selector: vscode.DocumentSelector, provider: vscode.SignatureHelpProvider, triggerCharacters: string[]): vscode.Disposable;
    $provideSignatureHelp(handle: number, resource: URI, position: IPosition): TPromise<modes.SignatureHelp>;
    registerDocumentLinkProvider(selector: vscode.DocumentSelector, provider: vscode.DocumentLinkProvider): vscode.Disposable;
    $provideDocumentLinks(handle: number, resource: URI): TPromise<modes.ILink[]>;
    $resolveDocumentLink(handle: number, link: modes.ILink): TPromise<modes.ILink>;
    registerColorProvider(selector: vscode.DocumentSelector, provider: vscode.DocumentColorProvider): vscode.Disposable;
    $provideDocumentColors(handle: number, resource: URI): TPromise<IRawColorInfo[]>;
    setLanguageConfiguration(languageId: string, configuration: vscode.LanguageConfiguration): vscode.Disposable;
}
