import { IDisposable, Disposable } from 'vs/base/common/lifecycle';
import { IThemeService, ITheme } from 'vs/platform/theme/common/themeService';
import { Color } from 'vs/base/common/color';
export declare const TAB_ACTIVE_BACKGROUND: string;
export declare const TAB_INACTIVE_BACKGROUND: string;
export declare const TAB_BORDER: string;
export declare const TAB_ACTIVE_BORDER: string;
export declare const TAB_UNFOCUSED_ACTIVE_BORDER: string;
export declare const TAB_ACTIVE_FOREGROUND: string;
export declare const TAB_INACTIVE_FOREGROUND: string;
export declare const TAB_UNFOCUSED_ACTIVE_FOREGROUND: string;
export declare const TAB_UNFOCUSED_INACTIVE_FOREGROUND: string;
export declare const EDITOR_GROUP_BACKGROUND: string;
export declare const EDITOR_GROUP_HEADER_TABS_BACKGROUND: string;
export declare const EDITOR_GROUP_HEADER_TABS_BORDER: string;
export declare const EDITOR_GROUP_HEADER_NO_TABS_BACKGROUND: string;
export declare const EDITOR_GROUP_BORDER: string;
export declare const EDITOR_DRAG_AND_DROP_BACKGROUND: string;
export declare const PANEL_BACKGROUND: string;
export declare const PANEL_BORDER: string;
export declare const PANEL_ACTIVE_TITLE_FOREGROUND: string;
export declare const PANEL_INACTIVE_TITLE_FOREGROUND: string;
export declare const PANEL_ACTIVE_TITLE_BORDER: string;
export declare const STATUS_BAR_FOREGROUND: string;
export declare const STATUS_BAR_NO_FOLDER_FOREGROUND: string;
export declare const STATUS_BAR_BACKGROUND: string;
export declare const STATUS_BAR_NO_FOLDER_BACKGROUND: string;
export declare const STATUS_BAR_BORDER: string;
export declare const STATUS_BAR_NO_FOLDER_BORDER: string;
export declare const STATUS_BAR_ITEM_ACTIVE_BACKGROUND: string;
export declare const STATUS_BAR_ITEM_HOVER_BACKGROUND: string;
export declare const STATUS_BAR_PROMINENT_ITEM_BACKGROUND: string;
export declare const STATUS_BAR_PROMINENT_ITEM_HOVER_BACKGROUND: string;
export declare const ACTIVITY_BAR_BACKGROUND: string;
export declare const ACTIVITY_BAR_FOREGROUND: string;
export declare const ACTIVITY_BAR_BORDER: string;
export declare const ACTIVITY_BAR_DRAG_AND_DROP_BACKGROUND: string;
export declare const ACTIVITY_BAR_BADGE_BACKGROUND: string;
export declare const ACTIVITY_BAR_BADGE_FOREGROUND: string;
export declare const SIDE_BAR_BACKGROUND: string;
export declare const SIDE_BAR_FOREGROUND: string;
export declare const SIDE_BAR_BORDER: string;
export declare const SIDE_BAR_TITLE_FOREGROUND: string;
export declare const SIDE_BAR_DRAG_AND_DROP_BACKGROUND: string;
export declare const SIDE_BAR_SECTION_HEADER_BACKGROUND: string;
export declare const SIDE_BAR_SECTION_HEADER_FOREGROUND: string;
export declare const TITLE_BAR_ACTIVE_FOREGROUND: string;
export declare const TITLE_BAR_INACTIVE_FOREGROUND: string;
export declare const TITLE_BAR_ACTIVE_BACKGROUND: string;
export declare const TITLE_BAR_INACTIVE_BACKGROUND: string;
export declare const TITLE_BAR_BORDER: string;
export declare const NOTIFICATIONS_FOREGROUND: string;
export declare const NOTIFICATIONS_BACKGROUND: string;
export declare const NOTIFICATIONS_BUTTON_BACKGROUND: string;
export declare const NOTIFICATIONS_BUTTON_HOVER_BACKGROUND: string;
export declare const NOTIFICATIONS_BUTTON_FOREGROUND: string;
export declare const NOTIFICATIONS_INFO_BACKGROUND: string;
export declare const NOTIFICATIONS_INFO_FOREGROUND: string;
export declare const NOTIFICATIONS_WARNING_BACKGROUND: string;
export declare const NOTIFICATIONS_WARNING_FOREGROUND: string;
export declare const NOTIFICATIONS_ERROR_BACKGROUND: string;
export declare const NOTIFICATIONS_ERROR_FOREGROUND: string;
/**
 * Base class for all themable workbench components.
 */
export declare class Themable extends Disposable {
    protected themeService: IThemeService;
    private _toUnbind;
    private theme;
    constructor(themeService: IThemeService);
    protected readonly toUnbind: IDisposable[];
    protected onThemeChange(theme: ITheme): void;
    protected updateStyles(): void;
    protected getColor(id: string, modify?: (color: Color, theme: ITheme) => Color): string;
    dispose(): void;
}
