import 'vs/css!./renameInputField';
import { IDisposable } from 'vs/base/common/lifecycle';
import { TPromise } from 'vs/base/common/winjs.base';
import { Range } from 'vs/editor/common/core/range';
import { ICodeEditor, IContentWidget, IContentWidgetPosition } from 'vs/editor/browser/editorBrowser';
import { IThemeService } from 'vs/platform/theme/common/themeService';
export default class RenameInputField implements IContentWidget, IDisposable {
    private themeService;
    private _editor;
    private _position;
    private _domNode;
    private _inputField;
    private _visible;
    private _disposables;
    allowEditorOverflow: boolean;
    constructor(editor: ICodeEditor, themeService: IThemeService);
    private onThemeChange(theme);
    dispose(): void;
    getId(): string;
    getDomNode(): HTMLElement;
    private updateStyles(theme);
    private updateFont();
    getPosition(): IContentWidgetPosition;
    private _currentAcceptInput;
    private _currentCancelInput;
    acceptInput(): void;
    cancelInput(): void;
    getInput(where: Range, value: string, selectionStart: number, selectionEnd: number): TPromise<string>;
    private _show();
    private _hide();
}
