import { IEnvironmentService } from 'vs/platform/environment/common/environment';
import { IConfigurationService } from 'vs/platform/configuration/common/configuration';
import { ITelemetryService } from 'vs/platform/telemetry/common/telemetry';
import { IUpdateService } from 'vs/platform/update/common/update';
import { IInstantiationService } from 'vs/platform/instantiation/common/instantiation';
import { IWindowsMainService } from 'vs/platform/windows/electron-main/windows';
import { IHistoryMainService } from 'vs/platform/history/common/history';
import { IWorkspacesMainService } from 'vs/platform/workspaces/common/workspaces';
export declare class CodeMenu {
    private updateService;
    private configurationService;
    private windowsService;
    private environmentService;
    private telemetryService;
    private historyService;
    private workspacesService;
    private static MAX_MENU_RECENT_ENTRIES;
    private currentAutoSaveSetting;
    private currentMultiCursorModifierSetting;
    private currentSidebarLocation;
    private currentStatusbarVisible;
    private currentActivityBarVisible;
    private currentEnableMenuBarMnemonics;
    private isQuitting;
    private appMenuInstalled;
    private menuUpdater;
    private keybindingsResolver;
    private extensionViewlets;
    private closeFolder;
    private closeWorkspace;
    private saveWorkspaceAs;
    constructor(updateService: IUpdateService, instantiationService: IInstantiationService, configurationService: IConfigurationService, windowsService: IWindowsMainService, environmentService: IEnvironmentService, telemetryService: ITelemetryService, historyService: IHistoryMainService, workspacesService: IWorkspacesMainService);
    private registerListeners();
    private onConfigurationUpdated(config, handleMenu?);
    private updateMenu();
    private doUpdateMenu();
    private onWindowsCountChanged(e);
    private updateWorkspaceMenuItems();
    private install();
    private setMacApplicationMenu(macApplicationMenu);
    private setFileMenu(fileMenu);
    private getPreferencesMenu();
    private setOpenRecentMenu(openRecentMenu);
    private createOpenRecentMenuItem(workspace, commandId, isFile);
    private isOptionClick(event);
    private createRoleMenuItem(label, commandId, role);
    private setEditMenu(winLinuxEditMenu);
    private setSelectionMenu(winLinuxEditMenu);
    private setViewMenu(viewMenu);
    private setGotoMenu(gotoMenu);
    private setDebugMenu(debugMenu);
    private setMacWindowMenu(macWindowMenu);
    private toggleDevTools();
    private setHelpMenu(helpMenu);
    private setTaskMenu(taskMenu);
    private openAccessibilityOptions();
    private getUpdateMenuItems();
    private createMenuItem(label, commandId, enabled?, checked?);
    private createMenuItem(label, click, enabled?, checked?);
    private createDevToolsAwareMenuItem(label, commandId, devToolsFocusedFn);
    private withKeybinding(commandId, options);
    private likeAction(commandId, options, setAccelerator?);
    private openAboutDialog();
    private openUrl(url, id);
    private reportMenuActionTelemetry(id);
    private mnemonicLabel(label);
}
