import 'vs/css!vs/workbench/parts/debug/browser/media/debugActionsWidget';
import { IPartService } from 'vs/workbench/services/part/common/partService';
import { IWorkbenchContribution } from 'vs/workbench/common/contributions';
import { IDebugService } from 'vs/workbench/parts/debug/common/debug';
import { IInstantiationService } from 'vs/platform/instantiation/common/instantiation';
import { IConfigurationService } from 'vs/platform/configuration/common/configuration';
import { IStorageService } from 'vs/platform/storage/common/storage';
import { IMessageService } from 'vs/platform/message/common/message';
import { ITelemetryService } from 'vs/platform/telemetry/common/telemetry';
import { Themable } from 'vs/workbench/common/theme';
import { IThemeService } from 'vs/platform/theme/common/themeService';
export declare const debugToolBarBackground: string;
export declare class DebugActionsWidget extends Themable implements IWorkbenchContribution {
    private messageService;
    private telemetryService;
    private debugService;
    private instantiationService;
    private partService;
    private storageService;
    private configurationService;
    private static ID;
    private $el;
    private dragArea;
    private actionBar;
    private allActions;
    private activeActions;
    private isVisible;
    private isBuilt;
    constructor(messageService: IMessageService, telemetryService: ITelemetryService, debugService: IDebugService, instantiationService: IInstantiationService, partService: IPartService, storageService: IStorageService, configurationService: IConfigurationService, themeService: IThemeService);
    private registerListeners();
    private storePosition();
    protected updateStyles(): void;
    private positionDebugWidget();
    private setXCoordinate(x?);
    getId(): string;
    private update(state);
    private show();
    private hide();
    private getActions();
    dispose(): void;
}
