import 'vs/css!./media/extensionsViewlet';
import { TPromise } from 'vs/base/common/winjs.base';
import { IWorkbenchContribution } from 'vs/workbench/common/contributions';
import { Builder, Dimension } from 'vs/base/browser/builder';
import { IAction } from 'vs/base/common/actions';
import { IViewletService } from 'vs/workbench/services/viewlet/browser/viewlet';
import { ITelemetryService } from 'vs/platform/telemetry/common/telemetry';
import { IInstantiationService } from 'vs/platform/instantiation/common/instantiation';
import { IExtensionService } from 'vs/platform/extensions/common/extensions';
import { IExtensionsWorkbenchService, IExtensionsViewlet } from '../common/extensions';
import { IExtensionManagementService } from 'vs/platform/extensionManagement/common/extensionManagement';
import { IProgressService } from 'vs/platform/progress/common/progress';
import { IWorkbenchEditorService } from 'vs/workbench/services/editor/common/editorService';
import { IEditorGroupService } from 'vs/workbench/services/group/common/groupService';
import { IMessageService } from 'vs/platform/message/common/message';
import { IActivityBarService } from 'vs/workbench/services/activity/common/activityBarService';
import { IThemeService } from 'vs/platform/theme/common/themeService';
import { IConfigurationService } from 'vs/platform/configuration/common/configuration';
import { IViewDescriptor } from 'vs/workbench/parts/views/browser/viewsRegistry';
import { PersistentViewsViewlet, IView } from 'vs/workbench/parts/views/browser/views';
import { IStorageService } from 'vs/platform/storage/common/storage';
import { IWorkspaceContextService } from 'vs/platform/workspace/common/workspace';
import { IContextKeyService } from 'vs/platform/contextkey/common/contextkey';
import { IContextMenuService } from 'vs/platform/contextview/browser/contextView';
export declare class ExtensionsViewlet extends PersistentViewsViewlet implements IExtensionsViewlet {
    private progressService;
    private editorService;
    private editorInputService;
    private extensionsWorkbenchService;
    private extensionManagementService;
    private messageService;
    private viewletService;
    private configurationService;
    private onSearchChange;
    private extensionsViewletVisibleContextKey;
    private searchExtensionsContextKey;
    private searchInstalledExtensionsContextKey;
    private searchRecommendedExtensionsContextKey;
    private searchDelayer;
    private root;
    private searchBox;
    private extensionsBox;
    private primaryActions;
    private secondaryActions;
    private disposables;
    private isAutoUpdateEnabled;
    constructor(telemetryService: ITelemetryService, progressService: IProgressService, instantiationService: IInstantiationService, editorService: IWorkbenchEditorService, editorInputService: IEditorGroupService, extensionsWorkbenchService: IExtensionsWorkbenchService, extensionManagementService: IExtensionManagementService, messageService: IMessageService, viewletService: IViewletService, themeService: IThemeService, configurationService: IConfigurationService, storageService: IStorageService, contextService: IWorkspaceContextService, contextKeyService: IContextKeyService, contextMenuService: IContextMenuService, extensionService: IExtensionService);
    private registerViews();
    private createMarketPlaceExtensionsListViewDescriptor();
    private createInstalledExtensionsListViewDescriptor();
    private createSearchInstalledExtensionsListViewDescriptor();
    private createRecommendedExtensionsListViewDescriptor();
    create(parent: Builder): TPromise<void>;
    updateStyles(): void;
    setVisible(visible: boolean): TPromise<void>;
    focus(): void;
    layout(dimension: Dimension): void;
    getOptimalWidth(): number;
    getActions(): IAction[];
    getSecondaryActions(): IAction[];
    search(value: string): void;
    private triggerSearch(immediate?);
    private doSearch();
    protected updateViews(unregisteredViews?: IViewDescriptor[], showAll?: boolean): TPromise<IView[]>;
    private count();
    private onEscape();
    private onEnter();
    private onUpArrow();
    private onDownArrow();
    private onPageUpArrow();
    private onPageDownArrow();
    private onViewletOpen(viewlet);
    private progress<T>(promise);
    private onError(err);
    dispose(): void;
}
export declare class StatusUpdater implements IWorkbenchContribution {
    private activityBarService;
    private extensionsWorkbenchService;
    private disposables;
    private badgeHandle;
    constructor(activityBarService: IActivityBarService, extensionsWorkbenchService: IExtensionsWorkbenchService);
    getId(): string;
    private onServiceChange();
    dispose(): void;
}
